language: python
python:
  - "2.7"
script: python run_tests.py
env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
  - DJANGO_VERSION=1.9.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q instal