language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - coverage run --source=crudbuilder runtests.py
env:
  matrix:
   - DJANGO="1.8.2"
   - DJANGO="1.9.2"
   - DJANGO="1.10"
   - DJANGO="1.11.7"

matrix:
  exclude:
    # Django 1.9+ no longer supports python 3.2/3.3
    - python: "3.3"
      env: DJANGO="1.9.2"
    - python: "3.3"
      env: DJANGO="1.10"

install:
  - pip install -q Django==$DJANGO
  - python setup.py -q install
  - pip install coveralls
after_success:
  coveralls